import java.util.Random;
import java.util.UUID;

public class Card {
	final UUID uuid = UUID.randomUUID();
	Long cardNumber;
	int pinNumber;


	Card(int pinNumber) {
		//TODO autogenerated cardNumber >16c
		this.cardNumber = 1000000000000000L + new Random().nextLong(9000000000000000L);
		this.pinNumber = pinNumber;
	}

	// Méthode de dépôt
	// faire valider le depot
	boolean deposit(int amount, int pinNumberGiven) {
		return pinNumberGiven == pinNumber;
	}

	// Méthode de retrait
	boolean takeout(int amount, int pinNumberGiven) {
		return pinNumberGiven == pinNumber;
	}
}
